# ── Contracts (generated by pass-1-contracts-agent) ──────────────────────
"""Type contracts for the calculator module.

Entities derived from:
  - design.mmd   : Placeholder; file is empty. No state transitions diagrammed.
                   Implication: module needs public arithmetic functions.
  - spec.gherkin : Feature "calculator" with scenarios covering the empty state.
                   Explicit reference: add(2, 3). Domain: basic arithmetic.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


# ── Domain types ──────────────────────────────────────────────────────────

Number = int | float
"""Numeric operand type. Both int and float are accepted by all operations.

See spec.gherkin: add(2, 3) — both operands are int literals, but the domain
implies float support (e.g. division results).
"""


class CalculatorInput(BaseModel):
    """Input schema for a binary arithmetic operation.

    Corresponds to the argument list of any two-operand function (e.g. add).
    See spec.gherkin: Scenario "Edge case — attempting to call a function"
    references add(2, 3).
    """

    operand_a: Number = Field(..., description="Left-hand / first operand")
    operand_b: Number = Field(..., description="Right-hand / second operand")


class CalculatorResult(BaseModel):
    """Output schema for an arithmetic operation.

    Captures the result value alongside the operation name for traceability.
    """

    result: Number
    operation: str = Field(..., description="Name of the operation performed (e.g. 'add')")


# ── Error conditions ──────────────────────────────────────────────────────

class DivisionByZeroError(ValueError):
    """Raised when a division (or modulus) operation receives a zero divisor.

    Derives from spec.gherkin error-case pattern: operations must surface
    meaningful errors rather than silently failing.
    """

    def __init__(self, operation: str) -> None:
        super().__init__(f"{operation}: division by zero is undefined")


# ── Public function contracts ─────────────────────────────────────────────
# All bodies are stubs (raise NotImplementedError).
# Implementation is the responsibility of Pass 3 (Core Implementation Agent).


def add(a: Number, b: Number) -> Number:
    """Return the sum of two numbers.

    Explicitly referenced in spec.gherkin:
      Scenario "Edge case — attempting to call a function on the empty module"
      When I attempt to call "add(2, 3)" on the module
    """
    raise NotImplementedError


def subtract(a: Number, b: Number) -> Number:
    """Return the difference (a - b) of two numbers.

    Implied by the calculator domain (design.mmd / spec.gherkin).
    """
    raise NotImplementedError


def multiply(a: Number, b: Number) -> Number:
    """Return the product (a * b) of two numbers.

    Implied by the calculator domain (design.mmd / spec.gherkin).
    """
    raise NotImplementedError


def divide(a: Number, b: Number) -> float:
    """Return the quotient (a / b) of two numbers.

    Returns float to preserve precision even for integer operands.
    Raises DivisionByZeroError when b == 0.

    Implied by the calculator domain (design.mmd / spec.gherkin).
    """
    raise NotImplementedError